name: "queries"
version: "1.0.0"
config-version: 2

profile: "smfp"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"


vars:
  # Internal variables
  DBT_USER: "{{ env_var('DBT_USER', 'dev_fantasma') }}"

  # BigQuery Monitoring
  bq_region: 'us'
  input_gcp_projects: ['rj-smfp']
  enable_gcp_bigquery_audit_logs: false
  gcp_billing_export_storage_project: 'rj-smfp'
  gcp_billing_export_dataset: 'gerenciamento_bigquery_billing'
  gcp_billing_export_table: 'gcp_billing_export'
  enable_gcp_billing_export: false
  gcp_bigquery_audit_logs_storage_project: 'rj-smfp'
  gcp_bigquery_audit_logs_dataset: 'gerenciamento_bigquery_audit_logs'
  gcp_bigquery_audit_logs_table: 'gcp_audit_logs'
  google_information_schema_model_materialization: 'ephemeral'


models:
  +persist_docs:
    relation: true
    columns: true
  dbt_bigquery_monitoring:
    +schema: "gerenciamento_bigquery_monitoring"

  queries:
    raw:
      +tags: "raw"
      ergon:
        +tags: "daily"
      sigma:
        +tags: "daily"
    mart:
      +tags: "mart"
      ergon_saude:
        +tags: "daily"
