smfp:
  target: dev
  outputs:
    dev:
      dataset: dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /tmp/credentials.json
      location: US
      method: service-account
      priority: interactive
      project: rj-smfp-dev
      threads: 8
      type: bigquery
    prod:
      dataset: dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /tmp/credentials.json
      location: US
      method: service-account
      priority: interactive
      project: rj-smfp
      threads: 8
      type: bigquery

