[project]
name = "queries-rj-smfp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-bigquery>=1.9.1",
    "dbt-core>=1.9.3",
]
