SELECT 
    SAFE_CAST(REGEXP_REPLACE(TRIM(numfunc), r'\.0$', '') AS STRING) AS id_funcionario,
    SAFE_CAST(REGEXP_REPLACE(TRIM(numvinc), r'\.0$', '') AS STRING) AS id_vinculo,
    SAFE_CAST(TRIM(vantagem) AS STRING) AS nome_vantagem,
    SAFE_CAST(TRIM(dtini) AS STRING) AS data_inicio,
    SAFE_CAST(TRIM(dtfim) AS STRING) AS data_final,
    SAFE_CAST(TRIM(valor) AS STRING) AS valor_vantagem,
    SAFE_CAST(TRIM(info) AS STRING) AS informacao_atributo,
    SAFE_CAST(TRIM(tipo_incorporacao) AS STRING) AS tipo_incorporacao_cargo_fiducia,
    SAFE_CAST(TRIM(perc_inc_funcao) AS STRING) AS percentual_incorporacao_cargo_fiducia,
    SAFE_CAST(TRIM(inc_tabelavenc) AS STRING) AS incide_tabela_vencimentos,
    SAFE_CAST(TRIM(inc_referencia) AS STRING) AS incide_tabela_simbolo,
    SAFE_CAST(TRIM(obs) AS STRING) AS observacoes,
    SAFE_CAST(TRIM(valor2) AS STRING) AS valor_complementar,
    SAFE_CAST(TRIM(info2) AS STRING) AS informacao_complementar,
    SAFE_CAST(TRIM(valor3) AS STRING) AS valor_complementar_2,
    SAFE_CAST(TRIM(info3) AS STRING) AS informacao_complementar_2,
    SAFE_CAST(TRIM(valor4) AS STRING) AS valor_coplementar_3,
    SAFE_CAST(TRIM(info4) AS STRING) AS informacao_complementar_3,
    SAFE_CAST(TRIM(valor5) AS STRING) AS valor_complementar_4,
    SAFE_CAST(TRIM(info5) AS STRING) AS informacao_complementar_4,
    SAFE_CAST(TRIM(valor6) AS STRING) AS valor_complementar_5,
    SAFE_CAST(TRIM(info6) AS STRING) AS informacao_complementar_5,
    SAFE_CAST(TRIM(flex_campo_05) AS STRING) AS valor_incorporado,
    SAFE_CAST(REGEXP_REPLACE(TRIM(emp_codigo), r'\.0$', '') AS STRING) AS id_empresa,
    SAFE_CAST(REGEXP_REPLACE(TRIM(chavevant), r'\.0$', '') AS STRING) AS id_vantagem,
FROM rj-smfp.recursos_humanos_ergon_staging.vantagens AS t