SELECT 
    SAFE_CAST(REGEXP_REPLACE(numfunc, r'\.0$', '') AS STRING) AS id_funcionario,
    SAFE_CAST(REGEXP_REPLACE(numero, r'\.0$', '') AS STRING) AS id_vinculo,
    SAFE_CAST(tipovinc AS STRING) AS tipo,
    SAFE_CAST(dtnom AS DATE) AS data_nomeacao,
    SAFE_CAST(dtposse AS DATE) AS data_posse,
    SAFE_CAST(dtexerc AS DATE) AS data_exercicio,
    SAFE_CAST(REGEXP_REPLACE(regimejur, r'\.0$', '') AS STRING) AS regime_juridico,
    SAFE_CAST(categoria AS STRING) AS categoria,
    SAFE_CAST(desconta_ir AS STRING) AS desconta_ir,
    SAFE_CAST(motivo AS STRING) AS descricao_provimento,
    SAFE_CAST(classifconc AS STRING) AS classificacao_concurso,
    SAFE_CAST(dtini_cessao AS DATE) AS data_inicio_cessao,
    SAFE_CAST(dtfim_cessao AS DATE) AS data_fim_cessao,
    SAFE_CAST(dtconc AS DATE) AS data_concurso,
    SAFE_CAST(dtopfgts AS DATE) AS data_fgts,
    SAFE_CAST(dtinicontr AS DATE) AS data_inicio_contrato,
    SAFE_CAST(dtfimcontr AS DATE) AS data_fim_contrato,
    SAFE_CAST(dtprorrogcontr AS DATE) AS data_prorrogacao_contrato,
    SAFE_CAST(dtaposent AS DATE) AS data_aposentadoria,
    SAFE_CAST(tipoapos AS STRING) AS tipo_aposentadoria,
    SAFE_CAST(dtvac AS DATE) AS data_vacancia,
    SAFE_CAST(REGEXP_REPLACE(formavac, r'\.0$', '') AS STRING) AS id_vacancia,
    SAFE_CAST(REGEXP_REPLACE(numvincant, r'\.0$', '') AS STRING) AS id_vinculo_anterior,
    SAFE_CAST(REGEXP_REPLACE(numvincpos, r'\.0$', '') AS STRING) AS id_vinculo_posterior,
    SAFE_CAST(tipoorg_req AS STRING) AS tipo_orgao_origem,
    SAFE_CAST(funcao_req AS STRING) AS funcao_origem_requisicao,
    SAFE_CAST(fone_req AS STRING) AS telefone_requisicao,
    SAFE_CAST(motivovac AS STRING) AS motivo_vacancia,
    SAFE_CAST(REGEXP_REPLACE(matric, r'\.0$', '') AS STRING) AS id_matricula_vinculo,
    SAFE_CAST(orgao_ext_req AS STRING) AS orgao_origem_requisicao,
    SAFE_CAST(tipo_onus_req AS STRING) AS tipo_onus_requisicao,
    SAFE_CAST(tipo_ressarc_req AS STRING) AS tipo_ressarcimento_requisicao,
    SAFE_CAST(tipo_req AS STRING) AS tipo_requisicao,
    SAFE_CAST(dt_pgto_ate AS DATE) AS data_pagamento_requisicao,
    SAFE_CAST(REGEXP_REPLACE(flex_campo_01, r'\.0$', '') AS STRING) AS origem_servidor_cedido,
    SAFE_CAST(REGEXP_REPLACE(flex_campo_05, r'\.0$', '') AS STRING) AS id_processo_origem,
    SAFE_CAST(flex_campo_09 AS STRING) AS contrato_suspenso,
    SAFE_CAST(flex_campo_17 AS STRING) AS professor,
    SAFE_CAST(flex_campo_18 AS STRING) AS cota,
    SAFE_CAST(REGEXP_REPLACE(emp_codigo, r'\.0$', '') AS STRING) AS id_empresa,
    SAFE_CAST(dt_homolog AS DATE) AS data_homologacao_aposentadoria,
FROM rj-smfp.recursos_humanos_ergon_staging.vinculo AS t