SELECT 
    SAFE_CAST(REGEXP_REPLACE(LANCAMENTO, r'\.0$', '') AS STRING) AS id_lancamento,
    SAFE_CAST(MES_ANO AS DATE) AS data_folha,
    SAFE_CAST(DTEXERC AS DATE) AS data_exercicio,
    SAFE_CAST(DTAPOSENT AS DATE) AS data_aposentadoria,
    SAFE_CAST(DTVAC AS DATE) AS data_vacancia,
    SAFE_CAST(DATA_CREDITO AS DATE) AS data_credito,
    SAFE_CAST(REGEXP_REPLACE(NUMFUNC, r'\.0$', '') AS STRING) AS id_funcao,
    SAFE_CAST(REGEXP_REPLACE(NUMVINC, r'\.0$', '') AS STRING) AS id_vinculo,
    SAFE_CAST(REGEXP_REPLACE(NUMERO, r'\.0$', '') AS INT64) AS numero_folha,
    SAFE_CAST(RUBRICA AS STRING) AS rubrica,
    SAFE_CAST(SETOR AS STRING) AS setor,
    SAFE_CAST(REGEXP_REPLACE(VALORVAN, r',', '.') AS FLOAT64) AS valor_bruto,    SAFE_CAST(REGEXP_REPLACE(VALORDES, r',', '.') AS FLOAT64) AS valor_descontos,    SAFE_CAST(REGEXP_REPLACE(VALORLIQ, r'\.0$', '') AS FLOAT64) AS valor_liquido,
    SAFE_CAST(REGEXP_REPLACE(NUMPENS, r'\.0$', '') AS INT64) AS pensionistas,
    SAFE_CAST(REGEXP_REPLACE(NUMDEPEN, r'\.0$', '') AS INT64) AS dependente,
    SAFE_CAST(REGEXP_REPLACE(AGENCIA, r'\.0$', '') AS INT64) AS agencia_banco,
    SAFE_CAST(REGEXP_REPLACE(BANCO, r'\.0$', '') AS INT64) AS banco,
    SAFE_CAST(REGEXP_REPLACE(CONTA, r'\.0$', '') AS INT64) AS conta_banco,
    SAFE_CAST(CARGO AS STRING) AS cargo,
    SAFE_CAST(SUBCATEGORIA AS STRING) AS cargo_subcategoria,
    SAFE_CAST(REGEXP_REPLACE(REFERENCIA, r'\.0$', '') AS STRING) AS id_referencia,
    SAFE_CAST(FUNCAO AS STRING) AS funcao,
    SAFE_CAST(NOME AS STRING) AS nome_fita_banco,
    SAFE_CAST(REGEXP_REPLACE(EMP_CODIGO, r'\.0$', '') AS STRING) AS id_empresa,
    SAFE_CAST(REGEXP_REPLACE(FICHA, r'\.0$', '') AS STRING) AS id_ficha,
    SAFE_CAST(REGEXP_REPLACE(REGIMEJUR, r'\.0$', '') AS STRING) AS regime_juridico,
    SAFE_CAST(TIPOVINC AS STRING) AS tipo_vinculo,
    SAFE_CAST(CATEGORIA AS STRING) AS categoria,
    SAFE_CAST(CPF AS STRING) AS cpf,
    SAFE_CAST(REGEXP_REPLACE(FLEX_CAMPO_05, r'\.0$', '') AS STRING) AS id_lotacao,
    SAFE_CAST(REGEXP_REPLACE(JORNADA, r'\.0$', '') AS STRING) AS id_jornada,
FROM rj-smfp.administracao_recursos_humanos_ergon_staging.fita_banco AS t