SELECT 
    SAFE_CAST(REGEXP_REPLACE(NUMERO, r'\.0$', '') AS STRING) AS id_vinculo,
    SAFE_CAST(NOME AS STRING) AS nome,
    SAFE_CAST(FLEX_CAMPO_03 AS STRING) AS nome_social,
    SAFE_CAST(TRATAMENTO AS STRING) AS nome_tratamento,
    SAFE_CAST(SEXO AS STRING) AS sexo,
    SAFE_CAST(RACA AS STRING) AS raca_cor,
    SAFE_CAST(DEFICIENTE AS STRING) AS deficiente,
    SAFE_CAST(TIPODEFIC AS STRING) AS tipo_deficiencia,
    SAFE_CAST(DTNASC AS DATE) AS data_nascimento,
    SAFE_CAST(FLEX_CAMPO_69 AS STRING) AS pais_nascimento,
    SAFE_CAST(CIDNASC AS STRING) AS municipio_nascimento,
    SAFE_CAST(CIDADEENDER_COD AS STRING) AS municipio_moradia,
    SAFE_CAST(UFNASC AS STRING) AS sigla_uf_nascimento,
    SAFE_CAST(G_SANGUINEO AS STRING) AS grupo_sanguineo,
    SAFE_CAST(PAI AS STRING) AS nome_pai,
    SAFE_CAST(MAE AS STRING) AS nome_mae,
    SAFE_CAST(ESTCIVIL AS STRING) AS estado_civil,
    SAFE_CAST(REGEXP_REPLACE(ESCOLARIDADE, r'\.0$', '') AS STRING) AS escolaridade,
    SAFE_CAST(REGEXP_REPLACE(NACIONALIDADE, r'\.0$', '') AS STRING) AS nacionalidade,
    SAFE_CAST(TIPOLOGENDER AS STRING) AS tipo_logradouro,
    SAFE_CAST(NOMELOGENDER AS STRING) AS logradouro,
    SAFE_CAST(NUMENDER AS STRING) AS numero_porta,
    SAFE_CAST(COMPLENDER AS STRING) AS complemento_numero_porta,
    SAFE_CAST(BAIRROENDER AS STRING) AS bairro,
    SAFE_CAST(CIDADEENDER AS STRING) AS municipio,
    SAFE_CAST(UFENDER AS STRING) AS sigla_uf,
    SAFE_CAST(CEPENDER AS STRING) AS cep,
    SAFE_CAST(FLEX_CAMPO_89 AS STRING) AS cep_exterior,
    SAFE_CAST(NUMTEL_CELULAR AS STRING) AS celular,
    SAFE_CAST(TELEFONE AS STRING) AS telefone,
    SAFE_CAST(RAMAL AS STRING) AS ramal,
    SAFE_CAST(E_MAIL AS STRING) AS email,
    SAFE_CAST(FLEX_CAMPO_90 AS STRING) AS email_alternativo,
    SAFE_CAST(ANOPRIMEMP AS STRING) AS ano_primeiro_emprego,
    SAFE_CAST(FLEX_CAMPO_70 AS DATE) AS data_primeiro_emprego,
    SAFE_CAST(UFEMPANT AS STRING) AS sigla_uf_emprego_anterior,
    SAFE_CAST(FLEX_CAMPO_80 AS DATE) AS data_primeira_habitacao,
    SAFE_CAST(FLEX_CAMPO_51 AS STRING) AS deficiente_fisico,
    SAFE_CAST(FLEX_CAMPO_52 AS STRING) AS deficiente_visual,
    SAFE_CAST(FLEX_CAMPO_53 AS STRING) AS deficiente_auditivo,
    SAFE_CAST(FLEX_CAMPO_54 AS STRING) AS deficiente_mental,
    SAFE_CAST(FLEX_CAMPO_55 AS STRING) AS deficiente_intelectual,
    SAFE_CAST(REGEXP_REPLACE(NUMRG, r'\.0$', '') AS STRING) AS id_rg,
    SAFE_CAST(TIPORG AS STRING) AS tipo_rg,
    SAFE_CAST(ORGAORG AS STRING) AS emissor_rg,
    SAFE_CAST(UFRG AS STRING) AS sigla_uf_rg,
    SAFE_CAST(EXPEDRG AS DATE) AS data_expedicao_rg,
    SAFE_CAST(REGEXP_REPLACE(CPF, r'\.0$', '') AS STRING) AS id_cpf,
    SAFE_CAST(REGEXP_REPLACE(NUMCARTPRO, r'\.0$', '') AS STRING) AS id_ctps,
    SAFE_CAST(SERCARTPRO AS STRING) AS serie_ctps,
    SAFE_CAST(UFCARTPRO AS STRING) AS sigla_uf_ctps,
    SAFE_CAST(REGEXP_REPLACE(NUMTITEL, r'\.0$', '') AS STRING) AS id_titulo_eleitor,
    SAFE_CAST(ZONATITEL AS STRING) AS zona_eleitoral,
    SAFE_CAST(SECTITEL AS STRING) AS secao_eleitoral,
    SAFE_CAST(UFTITEL AS STRING) AS sigla_uf_titulo_eleitor,
    SAFE_CAST(REGEXP_REPLACE(NUMDOCMILI, r'\.0$', '') AS STRING) AS id_documento_militar,
    SAFE_CAST(SERDOCMILI AS STRING) AS serie_documento_militar,
    SAFE_CAST(CATMILI AS STRING) AS categoria_militar,
    SAFE_CAST(ORGAOMILI AS STRING) AS emissor_documento_militar,
    SAFE_CAST(UFDOCMILI AS STRING) AS sigla_uf_documento_militar,
    SAFE_CAST(REGEXP_REPLACE(CNH, r'\.0$', '') AS STRING) AS id_cnh,
    SAFE_CAST(CATCNH AS STRING) AS categoria_cnh,
    SAFE_CAST(REGEXP_REPLACE(VALIDCNH, r'\.0$', '') AS STRING) AS validade_cnh,
    SAFE_CAST(UFCNH AS STRING) AS sigla_uf_cnh,
    SAFE_CAST(FLEX_CAMPO_26 AS STRING) AS orgao_emissor_cnh,
    SAFE_CAST(FLEX_CAMPO_27 AS DATE) AS data_expedicao_cnh,
    SAFE_CAST(REGEXP_REPLACE(PISPASEP, r'\.0$', '') AS STRING) AS id_pispasep,
    SAFE_CAST(DATAPIS AS DATE) AS data_inicio_pis,
    SAFE_CAST(REGEXP_REPLACE(FLEX_CAMPO_40, r'\.0$', '') AS STRING) AS id_nis,
    SAFE_CAST(BANCOPIS AS STRING) AS numero_banco_nis,
    SAFE_CAST(REGEXP_REPLACE(IDENTPROF, r'\.0$', '') AS STRING) AS id_identidade_profissional,
    SAFE_CAST(REGEXP_REPLACE(TIPOIDPROF, r'\.0$', '') AS STRING) AS tipo_identidade_profissional,
    SAFE_CAST(REGEXP_REPLACE(FLEX_CAMPO_06, r'\.0$', '') AS STRING) AS id_ric,
    SAFE_CAST(FLEX_CAMPO_07 AS STRING) AS emissor_ric,
    SAFE_CAST(FLEX_CAMPO_08 AS DATE) AS data_emissao_ric,
    SAFE_CAST(FLEX_CAMPO_28 AS STRING) AS expedicao_documento_orgao_classe,
    SAFE_CAST(FLEX_CAMPO_30 AS STRING) AS emissor_documento_orgao_classe,
    SAFE_CAST(UF_IDENTPROF AS STRING) AS sigla_uf_documento_orgoao_classe,
    SAFE_CAST(FLEX_CAMPO_02 AS STRING) AS possui_impedimento,
    SAFE_CAST(BANCO AS STRING) AS numero_banco,
    SAFE_CAST(AGENCIA AS STRING) AS agencia_banco,
    SAFE_CAST(CONTA AS STRING) AS conta_banco,
    SAFE_CAST(FLEX_CAMPO_36 AS DATE) AS data_ultima_atualizacao_bancaria,
    SAFE_CAST(REGEXP_REPLACE(TIPODOC_CERT, r'\.0$', '') AS STRING) AS tipo_certidao,
    SAFE_CAST(REGEXP_REPLACE(NUM_CERT, r'\.0$', '') AS STRING) AS numero_certidao,
    SAFE_CAST(REGEXP_REPLACE(LIVRO_A_CERT, r'\.0$', '') AS STRING) AS livro_certidao,
    SAFE_CAST(REGEXP_REPLACE(FOLHA_CERT, r'\.0$', '') AS STRING) AS folha_certidao,
    SAFE_CAST(REGEXP_REPLACE(CARTORIO_CERT, r'\.0$', '') AS STRING) AS cartorio_ceridao,
    SAFE_CAST(REGEXP_REPLACE(UF_CART, r'\.0$', '') AS STRING) AS sigla_uf_cartorio_certidao,
    SAFE_CAST(REGEXP_REPLACE(MUNICIPIO_CART_COD, r'\.0$', '') AS STRING) AS municipio_emissor_certidao,
    SAFE_CAST(MUNICIPIO_CART AS STRING) AS municipio_cartorio_emissor_certudai,
    SAFE_CAST(REGEXP_REPLACE(MATRICULA_CERT, r'\.0$', '') AS STRING) AS matricula_certidao,
    SAFE_CAST(FLEX_CAMPO_16 AS STRING) AS trabalho_voluntario,
    SAFE_CAST(FLEX_CAMPO_17 AS STRING) AS interesse_trabalho_voluntario,
    SAFE_CAST(FLEX_CAMPO_18 AS STRING) AS interesse_projeto_olimpico,
    SAFE_CAST(FLEX_CAMPO_19 AS STRING) AS interesse_projeto_sociais,
    SAFE_CAST(REGEXP_REPLACE(FLEX_CAMPO_56, r'\.0$', '') AS STRING) AS recebe_beneficio_previdenciario,
    SAFE_CAST(FLEX_CAMPO_58 AS STRING) AS nome_posse_alteracao_sexo,
    SAFE_CAST(FLEX_CAMPO_59 AS STRING) AS sexo_posse_alteracao_sexo,
    SAFE_CAST(FLEX_CAMPO_60 AS DATE) AS data_alteracao_sexo,
    SAFE_CAST(REGEXP_REPLACE(FLEX_CAMPO_09, r'\.0$', '') AS STRING) AS id_rne,
    SAFE_CAST(CHEGBRASIL AS STRING) AS ano_chegada_brasil,
    SAFE_CAST(FLEX_CAMPO_10 AS STRING) AS emissor_rne,
    SAFE_CAST(FLEX_CAMPO_11 AS DATE) AS data_expedicao_rne,
    SAFE_CAST(FLEX_CAMPO_12 AS DATE) AS data_chegada_estrangeiro,
    SAFE_CAST(FLEX_CAMPO_13 AS DATE) AS data_naturalizacao,
    SAFE_CAST(FLEX_CAMPO_14 AS STRING) AS estrangeiro_casado_brasileiro,
    SAFE_CAST(FLEX_CAMPO_15 AS STRING) AS estrangeiro_filho_brasileiro,
    SAFE_CAST(FLEX_CAMPO_20 AS STRING) AS login_facebook,
    SAFE_CAST(FLEX_CAMPO_21 AS STRING) AS login_twitter,
    SAFE_CAST(FLEX_CAMPO_22 AS STRING) AS login_google_plus,
    SAFE_CAST(FLEX_CAMPO_23 AS STRING) AS login_instagram,
    SAFE_CAST(FLEX_CAMPO_24 AS STRING) AS login_linkedin,
    SAFE_CAST(FLEX_CAMPO_25 AS STRING) AS login_myspace,
FROM rj-smfp.administracao_recursos_humanos_ergon_staging.funcionario AS t