SELECT 
    SAFE_CAST(REGEXP_REPLACE(NUMFUNC, r'\.0$', '') AS STRING) AS id_funcionario,
    SAFE_CAST(REGEXP_REPLACE(NUMERO, r'\.0$', '') AS STRING) AS id_vinculo,
    SAFE_CAST(TIPOVINC AS STRING) AS tipo,
    SAFE_CAST(DTNOM AS DATE) AS data_nomeacao,
    SAFE_CAST(DTPOSSE AS DATE) AS data_posse,
    SAFE_CAST(DTEXERC AS DATE) AS data_exercicio,
    SAFE_CAST(REGEXP_REPLACE(REGIMEJUR, r'\.0$', '') AS STRING) AS regime_juridico,
    SAFE_CAST(CATEGORIA AS STRING) AS categoria,
    SAFE_CAST(DESCONTA_IR AS STRING) AS desconta_ir,
    SAFE_CAST(MOTIVO AS STRING) AS descricao_provimento,
    SAFE_CAST(CLASSIFCONC AS STRING) AS classificacao_concurso,
    SAFE_CAST(DTINI_CESSAO AS DATE) AS data_inicio_cessao,
    SAFE_CAST(DTFIM_CESSAO AS DATE) AS data_fim_cessao,
    SAFE_CAST(DTCONC AS DATE) AS data_concurso,
    SAFE_CAST(DTOPFGTS AS DATE) AS data_fgts,
    SAFE_CAST(DTINICONTR AS DATE) AS data_inicio_contrato,
    SAFE_CAST(DTFIMCONTR AS DATE) AS data_fim_contrato,
    SAFE_CAST(DTPRORROGCONTR AS DATE) AS data_prorrogacao_contrato,
    SAFE_CAST(DTAPOSENT AS DATE) AS data_aposentadoria,
    SAFE_CAST(TIPOAPOS AS STRING) AS tipo_aposentadoria,
    SAFE_CAST(DTVAC AS DATE) AS data_vacancia,
    SAFE_CAST(REGEXP_REPLACE(FORMAVAC, r'\.0$', '') AS STRING) AS id_vacancia,
    SAFE_CAST(REGEXP_REPLACE(NUMVINCANT, r'\.0$', '') AS STRING) AS id_vinculo_anterior,
    SAFE_CAST(REGEXP_REPLACE(NUMVINCPOS, r'\.0$', '') AS STRING) AS id_vinculo_posterior,
    SAFE_CAST(TIPOORG_REQ AS STRING) AS tipo_orgao_origem,
    SAFE_CAST(FUNCAO_REQ AS STRING) AS funcao_origem_requisicao,
    SAFE_CAST(FONE_REQ AS STRING) AS telefone_requisicao,
    SAFE_CAST(MOTIVOVAC AS STRING) AS motivo_vacancia,
    SAFE_CAST(REGEXP_REPLACE(MATRIC, r'\.0$', '') AS STRING) AS id_matricula_vinculo,
    SAFE_CAST(ORGAO_EXT_REQ AS STRING) AS orgao_origem_requisicao,
    SAFE_CAST(TIPO_ONUS_REQ AS STRING) AS tipo_onus_requisicao,
    SAFE_CAST(TIPO_RESSARC_REQ AS STRING) AS tipo_ressarcimento_requisicao,
    SAFE_CAST(TIPO_REQ AS STRING) AS tipo_requisicao,
    SAFE_CAST(DT_PGTO_ATE AS DATE) AS data_pagamento_requisicao,
    SAFE_CAST(REGEXP_REPLACE(FLEX_CAMPO_01, r'\.0$', '') AS STRING) AS origem_servidor_cedido,
    SAFE_CAST(REGEXP_REPLACE(FLEX_CAMPO_05, r'\.0$', '') AS STRING) AS id_processo_origem,
    SAFE_CAST(FLEX_CAMPO_09 AS STRING) AS contrato_suspenso,
    SAFE_CAST(FLEX_CAMPO_17 AS STRING) AS professor,
    SAFE_CAST(FLEX_CAMPO_18 AS STRING) AS cota,
    SAFE_CAST(REGEXP_REPLACE(EMP_CODIGO, r'\.0$', '') AS STRING) AS id_empresa,
    SAFE_CAST(DT_HOMOLOG AS DATE) AS data_homologacao_aposentadoria,
FROM rj-smfp.administracao_recursos_humanos_ergon_staging.vinculo AS t