{{
    config(
        alias='empresas',
        schema='brutos_ergon'
    )
}}

SELECT
    SAFE_CAST(REGEXP_REPLACE(CAST(EMPRESA AS STRING), r'\.0$', '') AS STRING) AS id_empresa,
    SAFE_CAST(NOME AS STRING) AS nome_empresa,
    SAFE_CAST(FANTASIA AS STRING) AS sigla,
    SAFE_CAST(RAZAO AS STRING) AS razao_social,
    SAFE_CAST(REGEXP_REPLACE(CAST(CGC AS STRING), r'\.0$', '') AS STRING) AS cnpj,
    SAFE_CAST(REGEXP_REPLACE(CAST(ATIV_ECON AS STRING), r'\.0$', '') AS STRING) AS atividade_economica,

    -- Colunas novas do schema
    SAFE_CAST(_airbyte_extracted_at AS DATE) AS updated_at,
    SAFE_CAST(CEP AS STRING) AS cep,
    SAFE_CAST(REGEXP_REPLACE(CAST(DDD AS STRING), r'\.0$', '') AS STRING) AS ddd,
    SAFE_CAST(REGEXP_REPLACE(CAST(FAX AS STRING), r'\.0$', '') AS STRING) AS fax,
    SAFE_CAST(WEB AS STRING) AS web,
    SAFE_CAST(REGEXP_REPLACE(CAST(CNAE AS STRING), r'\.0$', '') AS STRING) AS cnae,
    SAFE_CAST(REGEXP_REPLACE(CAST(FONE AS STRING), r'\.0$', '') AS STRING) AS fone,
    SAFE_CAST(REGEXP_REPLACE(CAST(BANCO AS STRING), r'\.0$', '') AS STRING) AS banco,
    SAFE_CAST(CONTA AS STRING) AS conta,
    SAFE_CAST(EMAIL AS STRING) AS email,
    SAFE_CAST(REGEXP_REPLACE(CAST(RAMAL AS STRING), r'\.0$', '') AS STRING) AS ramal,
    SAFE_CAST(REGEXP_REPLACE(CAST(ID_REG AS STRING), r'\.0$', '') AS STRING) AS id_reg,
    SAFE_CAST(AGENCIA AS STRING) AS agencia,
    SAFE_CAST(REGEXP_REPLACE(CAST(NAT_JUR AS STRING), r'\.0$', '') AS STRING) AS nat_jur,
    SAFE_CAST(CPF_RESP AS STRING) AS cpf_resp,
    SAFE_CAST(REGEXP_REPLACE(CAST(NUMENDER AS STRING), r'\.0$', '') AS STRING) AS numender,
    SAFE_CAST(PONTPROC AS STRING) AS pontproc,
    SAFE_CAST(REGEXP_REPLACE(CAST(PONTPUBL AS STRING), r'\.0$', '') AS STRING) AS pontpubl,
    SAFE_CAST(UF_SIGLA AS STRING) AS uf_sigla,
    SAFE_CAST(MUNICIPIO AS STRING) AS municipio,
    SAFE_CAST(REGEXP_REPLACE(CAST(LOG_CODIGO AS STRING), r'\.0$', '') AS STRING) AS log_codigo,
    SAFE_CAST(COMPLEMENTO AS STRING) AS complemento,
    SAFE_CAST(RESPONSAVEL AS STRING) AS responsavel,
    SAFE_CAST(REGEXP_REPLACE(CAST(CAIXA_POSTAL AS STRING), r'\.0$', '') AS STRING) AS caixa_postal,
    SAFE_CAST(REGEXP_REPLACE(CAST(ID_DOCUMENTO AS STRING), r'\.0$', '') AS STRING) AS id_documento,
    SAFE_CAST(FLEX_CAMPO_03 AS STRING) AS flex_campo_03,
    SAFE_CAST(FLEX_CAMPO_04 AS STRING) AS flex_campo_04,
    SAFE_CAST(FLEX_CAMPO_05 AS STRING) AS flex_campo_05,
    SAFE_CAST(FLEX_CAMPO_06 AS STRING) AS flex_campo_06,
    SAFE_CAST(FLEX_CAMPO_07 AS STRING) AS flex_campo_07,
    SAFE_CAST(FLEX_CAMPO_08 AS STRING) AS flex_campo_08,
    SAFE_CAST(REGEXP_REPLACE(CAST(CGC_DECLARANTE AS STRING), r'\.0$', '') AS STRING) AS cgc_declarante,
    SAFE_CAST(MBAIRRO_CODIGO AS STRING) AS mbairro_codigo,
    SAFE_CAST(NOMELOGRADOURO AS STRING) AS nomelogradouro,
    SAFE_CAST(TIPOLOGRADOURO AS STRING) AS tipologradouro,
    SAFE_CAST(MUNICIPIO_CODIGO AS STRING) AS municipio_codigo
FROM {{ source('brutos_ergon_staging', 'VW_DLK_ERG_EMPRESAS')}}