{{
    config(
        alias='funcionario',
        schema='brutos_ergon'
    )
}}

SELECT
    SAFE_CAST(REGEXP_REPLACE(CAST(NUMERO AS STRING), r'\.0$', '') AS STRING) AS id_vinculo,
    SAFE_CAST(NOME AS STRING) AS nome,
    SAFE_CAST(FLEX_CAMPO_03 AS STRING) AS nome_social,
    SAFE_CAST(TRATAMENTO AS STRING) AS nome_tratamento,
    SAFE_CAST(SEXO AS STRING) AS sexo,
    SAFE_CAST(CAST(RACA AS STRING) AS STRING) AS raca_cor,
    SAFE_CAST(DEFICIENTE AS STRING) AS deficiente,
    SAFE_CAST(TIPODEFIC AS STRING) AS tipo_deficiencia,
    SAFE_CAST(SAFE.PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E*S',DTNASC) AS DATE) AS data_nascimento,
    SAFE_CAST(FLEX_CAMPO_69 AS STRING) AS pais_nascimento,
    SAFE_CAST(CIDNASC AS STRING) AS municipio_nascimento,
    SAFE_CAST(CIDADEENDER_COD AS STRING) AS municipio_moradia,
    SAFE_CAST(UFNASC AS STRING) AS sigla_uf_nascimento,
    SAFE_CAST(G_SANGUINEO AS STRING) AS grupo_sanguineo,
    SAFE_CAST(PAI AS STRING) AS nome_pai,
    SAFE_CAST(MAE AS STRING) AS nome_mae,
    SAFE_CAST(ESTCIVIL AS STRING) AS estado_civil,
    SAFE_CAST(REGEXP_REPLACE(ESCOLARIDADE, r'\.0$', '') AS STRING) AS escolaridade,
    SAFE_CAST(REGEXP_REPLACE(CAST(NACIONALIDADE AS STRING), r'\.0$', '') AS STRING) AS nacionalidade,
    SAFE_CAST(TIPOLOGENDER AS STRING) AS tipo_logradouro,
    SAFE_CAST(NOMELOGENDER AS STRING) AS logradouro,
    SAFE_CAST(CAST(NUMENDER AS STRING) AS STRING) AS numero_porta,
    SAFE_CAST(COMPLENDER AS STRING) AS complemento_numero_porta,
    SAFE_CAST(BAIRROENDER AS STRING) AS bairro,
    SAFE_CAST(CIDADEENDER AS STRING) AS municipio,
    SAFE_CAST(UFENDER AS STRING) AS sigla_uf,
    SAFE_CAST(CAST(CEPENDER AS STRING) AS STRING) AS cep,
    SAFE_CAST(FLEX_CAMPO_89 AS STRING) AS cep_exterior,
    SAFE_CAST(NUMTEL_CELULAR AS STRING) AS celular,
    SAFE_CAST(TELEFONE AS STRING) AS telefone,
    SAFE_CAST(RAMAL AS STRING) AS ramal,
    SAFE_CAST(E_MAIL AS STRING) AS email,
    SAFE_CAST(FLEX_CAMPO_90 AS STRING) AS email_alternativo,
    SAFE_CAST(CAST(ANOPRIMEMP AS STRING) AS STRING) AS ano_primeiro_emprego,
    SAFE_CAST(SAFE.PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E*S',FLEX_CAMPO_70) AS DATE)  AS data_primeiro_emprego,
    SAFE_CAST(UFEMPANT AS STRING) AS sigla_uf_emprego_anterior,
    SAFE_CAST(SAFE.PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E*S',FLEX_CAMPO_80) AS DATE)  AS data_primeira_habitacao,
    SAFE_CAST(FLEX_CAMPO_51 AS STRING) AS deficiente_fisico,
    SAFE_CAST(FLEX_CAMPO_52 AS STRING) AS deficiente_visual,
    SAFE_CAST(FLEX_CAMPO_53 AS STRING) AS deficiente_auditivo,
    SAFE_CAST(FLEX_CAMPO_54 AS STRING) AS deficiente_mental,
    SAFE_CAST(FLEX_CAMPO_55 AS STRING) AS deficiente_intelectual,
    SAFE_CAST(REGEXP_REPLACE(NUMRG, r'\.0$', '') AS STRING) AS id_rg,
    SAFE_CAST(TIPORG AS STRING) AS tipo_rg,
    SAFE_CAST(ORGAORG AS STRING) AS emissor_rg,
    SAFE_CAST(UFRG AS STRING) AS sigla_uf_rg,
    SAFE_CAST(SAFE.PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E*S',EXPEDRG) AS DATE)  AS data_expedicao_rg,
    SAFE_CAST(REGEXP_REPLACE(CAST(CPF AS STRING), r'\.0$', '') AS STRING) AS id_cpf,
    SAFE_CAST(REGEXP_REPLACE(CAST(NUMCARTPRO AS STRING), r'\.0$', '') AS STRING) AS id_ctps,
    SAFE_CAST(SERCARTPRO AS STRING) AS serie_ctps,
    SAFE_CAST(UFCARTPRO AS STRING) AS sigla_uf_ctps,
    SAFE_CAST(REGEXP_REPLACE(CAST(NUMTITEL AS STRING), r'\.0$', '') AS STRING) AS id_titulo_eleitor,
    SAFE_CAST(CAST(ZONATITEL AS STRING) AS STRING) AS zona_eleitoral,
    SAFE_CAST(CAST(SECTITEL AS STRING) AS STRING) AS secao_eleitoral,
    SAFE_CAST(UFTITEL AS STRING) AS sigla_uf_titulo_eleitor,
    SAFE_CAST(REGEXP_REPLACE(CAST(NUMDOCMILI AS STRING), r'\.0$', '') AS STRING) AS id_documento_militar,
    SAFE_CAST(SERDOCMILI AS STRING) AS serie_documento_militar,
    SAFE_CAST(CATMILI AS STRING) AS categoria_militar,
    SAFE_CAST(ORGAOMILI AS STRING) AS emissor_documento_militar,
    SAFE_CAST(UFDOCMILI AS STRING) AS sigla_uf_documento_militar,
    SAFE_CAST(REGEXP_REPLACE(CAST(CNH AS STRING), r'\.0$', '') AS STRING) AS id_cnh,
    SAFE_CAST(CATCNH AS STRING) AS categoria_cnh,
    SAFE_CAST(REGEXP_REPLACE(VALIDCNH, r'\.0$', '') AS STRING) AS validade_cnh,
    SAFE_CAST(UFCNH AS STRING) AS sigla_uf_cnh,
    SAFE_CAST(FLEX_CAMPO_26 AS STRING) AS orgao_emissor_cnh,
    SAFE_CAST(SAFE.PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E*S',FLEX_CAMPO_27) AS DATE) AS data_expedicao_cnh,
    SAFE_CAST(REGEXP_REPLACE(CAST(PISPASEP AS STRING), r'\.0$', '') AS STRING) AS id_pispasep,
    SAFE_CAST(SAFE.PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E*S',DATAPIS) AS DATE) AS data_inicio_pis,
    SAFE_CAST(REGEXP_REPLACE(FLEX_CAMPO_40, r'\.0$', '') AS STRING) AS id_nis,
    SAFE_CAST(CAST(BANCOPIS AS STRING) AS STRING) AS numero_banco_nis,
    SAFE_CAST(REGEXP_REPLACE(IDENTPROF, r'\.0$', '') AS STRING) AS id_identidade_profissional,
    SAFE_CAST(REGEXP_REPLACE(TIPOIDPROF, r'\.0$', '') AS STRING) AS tipo_identidade_profissional,
    SAFE_CAST(REGEXP_REPLACE(FLEX_CAMPO_06, r'\.0$', '') AS STRING) AS id_ric,
    SAFE_CAST(FLEX_CAMPO_07 AS STRING) AS emissor_ric,
    SAFE_CAST(SAFE.PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E*S',FLEX_CAMPO_08) AS DATE) AS data_emissao_ric,
    SAFE_CAST(FLEX_CAMPO_28 AS STRING) AS expedicao_documento_orgao_classe,
    SAFE_CAST(FLEX_CAMPO_30 AS STRING) AS emissor_documento_orgao_classe,
    SAFE_CAST(UF_IDENTPROF AS STRING) AS sigla_uf_documento_orgao_classe,
    SAFE_CAST(FLEX_CAMPO_02 AS STRING) AS possui_impedimento,
    SAFE_CAST(CAST(BANCO AS STRING) AS STRING) AS numero_banco,
    SAFE_CAST(AGENCIA AS STRING) AS agencia_banco,
    SAFE_CAST(CONTA AS STRING) AS conta_banco,
    SAFE_CAST( SAFE.PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E*S',FLEX_CAMPO_36) AS DATE)  AS data_ultima_atualizacao_bancaria,
    SAFE_CAST(REGEXP_REPLACE(TIPODOC_CERT, r'\.0$', '') AS STRING) AS tipo_certidao,
    SAFE_CAST(REGEXP_REPLACE(CAST(NUM_CERT AS STRING), r'\.0$', '') AS STRING) AS livro_certidao,
    SAFE_CAST(REGEXP_REPLACE(FOLHA_CERT, r'\.0$', '') AS STRING) AS folha_certidao,
    SAFE_CAST(REGEXP_REPLACE(CARTORIO_CERT, r'\.0$', '') AS STRING) AS cartorio_ceridao,
    SAFE_CAST(REGEXP_REPLACE(UF_CART, r'\.0$', '') AS STRING) AS sigla_uf_cartorio_certidao,
    SAFE_CAST(REGEXP_REPLACE(MUNICIPIO_CART_COD, r'\.0$', '') AS STRING) AS municipio_emissor_certidao,
    SAFE_CAST(MUNICIPIO_CART AS STRING) AS municipio_cartorio_emissor_certudai,
    SAFE_CAST(REGEXP_REPLACE(MATRICULA_CERT, r'\.0$', '') AS STRING) AS matricula_certidao,
    SAFE_CAST(FLEX_CAMPO_16 AS STRING) AS trabalho_voluntario,
    SAFE_CAST(FLEX_CAMPO_17 AS STRING) AS interesse_trabalho_voluntario,
    SAFE_CAST(FLEX_CAMPO_18 AS STRING) AS interesse_projeto_olimpico,
    SAFE_CAST(FLEX_CAMPO_19 AS STRING) AS interesse_projetos_sociais,
    SAFE_CAST(REGEXP_REPLACE(FLEX_CAMPO_56, r'\.0$', '') AS STRING) AS recebe_beneficio_previdenciario,
    SAFE_CAST(FLEX_CAMPO_58 AS STRING) AS nome_posse_alteracao_sexo,
    SAFE_CAST(FLEX_CAMPO_59 AS STRING) AS sexo_posse_alteracao_sexo,
    SAFE_CAST(SAFE.PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E*S',FLEX_CAMPO_60) AS DATE)  AS data_alteracao_sexo,
    SAFE_CAST(REGEXP_REPLACE(FLEX_CAMPO_09, r'\.0$', '') AS STRING) AS id_rne,
    SAFE_CAST(CAST(CHEGBRASIL AS STRING) AS STRING) AS ano_chegada_brasil,
    SAFE_CAST(FLEX_CAMPO_10 AS STRING) AS emissor_rne,
    SAFE_CAST(SAFE.PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E*S',FLEX_CAMPO_11) AS DATE)  AS data_expedicao_rne,
    SAFE_CAST(SAFE.PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E*S',FLEX_CAMPO_12) AS DATE)  AS data_chegada_estrangeiro,
    SAFE_CAST(SAFE.PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E*S',FLEX_CAMPO_13) AS DATE)  AS data_naturalizacao,
    SAFE_CAST(FLEX_CAMPO_14 AS STRING) AS estrangeiro_casado_brasileiro,
    SAFE_CAST(FLEX_CAMPO_15 AS STRING) AS estrangeiro_filho_brasileiro,
    SAFE_CAST(FLEX_CAMPO_20 AS STRING) AS login_facebook,
    SAFE_CAST(FLEX_CAMPO_21 AS STRING) AS login_twitter,
    SAFE_CAST(FLEX_CAMPO_22 AS STRING) AS login_google_plus,
    SAFE_CAST(FLEX_CAMPO_23 AS STRING) AS login_instagram,
    SAFE_CAST(FLEX_CAMPO_24 AS STRING) AS login_linkedin,
    SAFE_CAST(FLEX_CAMPO_25 AS STRING) AS login_myspace

    -- Novos campos da tabela VW_DLK_ERG_FUNCIONARIOS
    , _airbyte_extracted_at as updated_at
    , SAFE_CAST(CAST(US AS STRING) AS STRING) AS US
    , SAFE_CAST(FOTO AS STRING) AS FOTO
    , SAFE_CAST(CAST(ID_REG AS STRING) AS STRING) AS ID_REG
    , SAFE_CAST(TIPOPAG AS STRING) AS TIPOPAG
    , SAFE_CAST(FLAG_WEB AS STRING) AS FLAG_WEB
    , SAFE_CAST(CAST(PONTPUBL AS STRING) AS STRING) AS PONTPUBL
    , SAFE_CAST(CAST(ID_PESSOA AS STRING) AS STRING) AS ID_PESSOA
    , SAFE_CAST(SAFE.PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E*S',DT_CERT_FIM) AS DATE)  AS DT_CERT_FIM
    , SAFE_CAST(SAFE.PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E*S',DT_RECADAST) AS DATE) AS DT_RECADAST
    , SAFE_CAST(UF_CART_FIM AS STRING) AS UF_CART_FIM
    , SAFE_CAST(LIVRO_A_CERT AS STRING) AS LIVRO_A_CERT
    , SAFE_CAST(CAST(NUM_CERT_FIM AS STRING) AS STRING) AS NUM_CERT_FIM
    , SAFE_CAST(TIPODOC_CERT_FIM AS STRING) AS TIPODOC_CERT_FIM
    , SAFE_CAST(FLEX_CAMPO_01 AS STRING) AS FLEX_CAMPO_01
    , SAFE_CAST(FLEX_CAMPO_04 AS STRING) AS FLEX_CAMPO_04
    , SAFE_CAST(FLEX_CAMPO_05 AS STRING) AS FLEX_CAMPO_05
    , SAFE_CAST(FLEX_CAMPO_29 AS STRING) AS FLEX_CAMPO_29
    , SAFE_CAST(FLEX_CAMPO_31 AS STRING) AS FLEX_CAMPO_31
    , SAFE_CAST(FLEX_CAMPO_32 AS STRING) AS FLEX_CAMPO_32
    , SAFE_CAST(FLEX_CAMPO_33 AS STRING) AS FLEX_CAMPO_33
    , SAFE_CAST(FLEX_CAMPO_34 AS STRING) AS FLEX_CAMPO_34
    , SAFE_CAST(FLEX_CAMPO_35 AS STRING) AS FLEX_CAMPO_35
    , SAFE_CAST(FLEX_CAMPO_37 AS STRING) AS FLEX_CAMPO_37
    , SAFE_CAST(FLEX_CAMPO_38 AS STRING) AS FLEX_CAMPO_38
    , SAFE_CAST(FLEX_CAMPO_39 AS STRING) AS FLEX_CAMPO_39
    , SAFE_CAST(FLEX_CAMPO_41 AS STRING) AS FLEX_CAMPO_41
    , SAFE_CAST(FLEX_CAMPO_42 AS STRING) AS FLEX_CAMPO_42
    , SAFE_CAST(FLEX_CAMPO_43 AS STRING) AS FLEX_CAMPO_43
    , SAFE_CAST(FLEX_CAMPO_44 AS STRING) AS FLEX_CAMPO_44
    , SAFE_CAST(FLEX_CAMPO_45 AS STRING) AS FLEX_CAMPO_45
    , SAFE_CAST(FLEX_CAMPO_46 AS STRING) AS FLEX_CAMPO_46
    , SAFE_CAST(FLEX_CAMPO_47 AS STRING) AS FLEX_CAMPO_47
    , SAFE_CAST(FLEX_CAMPO_48 AS STRING) AS FLEX_CAMPO_48
    , SAFE_CAST(FLEX_CAMPO_49 AS STRING) AS FLEX_CAMPO_49
    , SAFE_CAST(FLEX_CAMPO_50 AS STRING) AS FLEX_CAMPO_50
    , SAFE_CAST(FLEX_CAMPO_57 AS STRING) AS FLEX_CAMPO_57
    , SAFE_CAST(FLEX_CAMPO_61 AS STRING) AS FLEX_CAMPO_61
    , SAFE_CAST(FLEX_CAMPO_62 AS STRING) AS FLEX_CAMPO_62
    , SAFE_CAST(FLEX_CAMPO_63 AS STRING) AS FLEX_CAMPO_63
    , SAFE_CAST(FLEX_CAMPO_64 AS STRING) AS FLEX_CAMPO_64
    , SAFE_CAST(FLEX_CAMPO_65 AS STRING) AS FLEX_CAMPO_65
    , SAFE_CAST(FLEX_CAMPO_66 AS STRING) AS FLEX_CAMPO_66
    , SAFE_CAST(FLEX_CAMPO_67 AS STRING) AS FLEX_CAMPO_67
    , SAFE_CAST(FLEX_CAMPO_68 AS STRING) AS FLEX_CAMPO_68
    , SAFE_CAST(FLEX_CAMPO_71 AS STRING) AS FLEX_CAMPO_71
    , SAFE_CAST(FLEX_CAMPO_72 AS STRING) AS FLEX_CAMPO_72
    , SAFE_CAST(FLEX_CAMPO_73 AS STRING) AS FLEX_CAMPO_73
    , SAFE_CAST(FLEX_CAMPO_74 AS STRING) AS FLEX_CAMPO_74
    , SAFE_CAST(FLEX_CAMPO_75 AS STRING) AS FLEX_CAMPO_75
    , SAFE_CAST(FLEX_CAMPO_76 AS STRING) AS FLEX_CAMPO_76
    , SAFE_CAST(FLEX_CAMPO_77 AS STRING) AS FLEX_CAMPO_77
    , SAFE_CAST(FLEX_CAMPO_78 AS STRING) AS FLEX_CAMPO_78
    , SAFE_CAST(FLEX_CAMPO_79 AS STRING) AS FLEX_CAMPO_79
    , SAFE_CAST(FLEX_CAMPO_81 AS STRING) AS FLEX_CAMPO_81
    , SAFE_CAST(FLEX_CAMPO_82 AS STRING) AS FLEX_CAMPO_82
    , SAFE_CAST(FLEX_CAMPO_83 AS STRING) AS FLEX_CAMPO_83
    , SAFE_CAST(FLEX_CAMPO_84 AS STRING) AS FLEX_CAMPO_84
    , SAFE_CAST(FLEX_CAMPO_85 AS STRING) AS FLEX_CAMPO_85
    , SAFE_CAST(FLEX_CAMPO_86 AS STRING) AS FLEX_CAMPO_86
    , SAFE_CAST(FLEX_CAMPO_87 AS STRING) AS FLEX_CAMPO_87
    , SAFE_CAST(FLEX_CAMPO_88 AS STRING) AS FLEX_CAMPO_88
    , SAFE_CAST(FLEX_CAMPO_91 AS STRING) AS FLEX_CAMPO_91
    , SAFE_CAST(FLEX_CAMPO_92 AS STRING) AS FLEX_CAMPO_92
    , SAFE_CAST(FLEX_CAMPO_93 AS STRING) AS FLEX_CAMPO_93
    , SAFE_CAST(FLEX_CAMPO_94 AS STRING) AS FLEX_CAMPO_94
    , SAFE_CAST(FLEX_CAMPO_95 AS STRING) AS FLEX_CAMPO_95
    , SAFE_CAST(FLEX_CAMPO_96 AS STRING) AS FLEX_CAMPO_96
    , SAFE_CAST(FLEX_CAMPO_97 AS STRING) AS FLEX_CAMPO_97
    , SAFE_CAST(FLEX_CAMPO_98 AS STRING) AS FLEX_CAMPO_98
    , SAFE_CAST(FLEX_CAMPO_99 AS STRING) AS FLEX_CAMPO_99
    , SAFE_CAST(FLEX_CAMPO_100 AS STRING) AS FLEX_CAMPO_100
    , SAFE_CAST(FOLHA_CERT_FIM AS STRING) AS FOLHA_CERT_FIM
    , SAFE_CAST(LIVRO_CERT_FIM AS STRING) AS LIVRO_CERT_FIM
    , SAFE_CAST(CARTORIO_CERT_FIM AS STRING) AS CARTORIO_CERT_FIM
    , SAFE_CAST(MATRICULA_CERT_FIM AS STRING) AS MATRICULA_CERT_FIM
    , SAFE_CAST(MUNICIPIO_CART_FIM_COD AS STRING) AS MUNICIPIO_CART_FIM_COD
    , SAFE_CAST(GERA_PASEP AS STRING) AS GERA_PASEP
    , SAFE_CAST(INFORMARBB AS STRING) AS INFORMARBB

FROM {{ source('brutos_ergon_staging', 'VW_DLK_ERG_FUNCIONARIOS')}}