{{
    config(
        alias='cargo',
        schema='brutos_ergon'
    )
}}
SELECT
    SAFE_CAST(REGEXP_REPLACE(CAST(CARGO AS STRING), r'\.0$', '') AS STRING) AS id_cargo,
    SAFE_CAST(NOME AS STRING) AS nome,
    SAFE_CAST(CATEGORIA AS STRING) AS categoria,
    SAFE_CAST(SUBCATEGORIA AS STRING) AS subcategoria,
    SAFE_CAST(CONTROLE_VAGA AS STRING) AS tipo_controle_vaga,
    SAFE_CAST(REGEXP_REPLACE(ESCOLARIDADE, r'\.0$', '') AS STRING) AS escolaridade,
    SAFE_CAST(E_AGLUTINADOR AS STRING) AS aglutinador

    -- Novos campos da tabela VW_DLK_ERG_CARGOS_
    , _airbyte_extracted_at AS updated_at
    , SAFE_CAST(CAST(ID_REG AS STRING) AS STRING) AS ID_REG
    , SAFE_CAST(CAST(PONTLEI AS STRING) AS STRING) AS PONTLEI
    , SAFE_CAST(CAST(PONTPUBL AS STRING) AS STRING) AS PONTPUBL
    , SAFE_CAST(POR_REFER AS STRING) AS POR_REFER
    , SAFE_CAST(TIPO_CARGO AS STRING) AS TIPO_CARGO
    , SAFE_CAST(CAST(CARGO_AGLUT AS STRING) AS STRING) AS CARGO_AGLUT
    , SAFE_CAST( SAFE.PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E*S',DT_EXTINCAO) AS DATE) AS DT_EXTINCAO
    , SAFE_CAST(CARGO_FUNCAO AS STRING) AS CARGO_FUNCAO
    , SAFE_CAST(FLEX_CAMPO_09 AS STRING) AS FLEX_CAMPO_09
    , SAFE_CAST( SAFE.PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E*S',DT_CONTROLE_ACUM) AS DATE) AS DT_CONTROLE_ACUM
    , SAFE_CAST( SAFE.PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E*S',DT_INICIO_CONTR_VAGA) AS DATE) AS DT_INICIO_CONTR_VAGA

FROM {{ source('brutos_ergon_staging', 'VW_DLK_ERG_CARGOS_')}}