{{
    config(
        alias='setor',
        schema='brutos_ergon'
    )
}}
SELECT
    SAFE_CAST( SAFE.PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E*S',DATAINI) AS DATE) AS data_inicio,
    SAFE_CAST( SAFE.PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E*S',DATAFIM) AS DATE) AS data_fim,
    SAFE_CAST(REGEXP_REPLACE(PAISETOR, r'\.0$', '') AS STRING) AS id_setor_pai,
    SAFE_CAST(REGEXP_REPLACE(SETOR, r'\.0$', '') AS STRING) AS id_setor,
    SAFE_CAST(NOMESETOR AS STRING) AS nome,
    SAFE_CAST(NOMESETORLONGO AS STRING) AS nome_completo,
    SAFE_CAST(FLEX_CAMPO_01 AS STRING) AS sigla,
    SAFE_CAST(REGEXP_REPLACE(CAST(EMP_CODIGO AS STRING), r'\.0$', '') AS STRING) AS id_empresa,
    SAFE_CAST(REGEXP_REPLACE(FLEX_CAMPO_02, r'\.0$', '') AS STRING) AS id_empresa_prevrio,
    SAFE_CAST(REGEXP_REPLACE(FLEX_CAMPO_05, r'\.0$', '') AS STRING) AS id_secretaria,
    SAFE_CAST(EXTINTO AS STRING) AS extinto

    -- Novos campos da tabela VW_DLK_ERG_HSETOR_
    , _airbyte_extracted_at AS updated_at
    , SAFE_CAST(CAST(_airbyte_generation_id AS STRING) AS STRING) AS _airbyte_generation_id
    , SAFE_CAST(UF AS STRING) AS UF
    , SAFE_CAST(CEP AS STRING) AS CEP
    , SAFE_CAST(CAST(CGC AS STRING) AS STRING) AS CGC
    , SAFE_CAST(FAX AS STRING) AS FAX
    , SAFE_CAST(OBS AS STRING) AS OBS
    , SAFE_CAST(FONE AS STRING) AS FONE
    , SAFE_CAST(BAIRRO AS STRING) AS BAIRRO
    , SAFE_CAST(CIDADE AS STRING) AS CIDADE
    , SAFE_CAST(HLOCAL AS STRING) AS HLOCAL
    , SAFE_CAST(NOMELOG AS STRING) AS NOMELOG
    , SAFE_CAST(TIPOLOG AS STRING) AS TIPOLOG
    , SAFE_CAST(CAST(PONTPUBL AS STRING) AS STRING) AS PONTPUBL
    , SAFE_CAST(CAST(NUMEROLOG AS STRING) AS STRING) AS NUMEROLOG
    , SAFE_CAST(PAISETOR1 AS STRING) AS PAISETOR1
    , SAFE_CAST(PAISETOR2 AS STRING) AS PAISETOR2
    , SAFE_CAST(PAISETOR3 AS STRING) AS PAISETOR3
    , SAFE_CAST(PAISETOR4 AS STRING) AS PAISETOR4
    , SAFE_CAST(TIPOLOGIA AS STRING) AS TIPOLOGIA
    , SAFE_CAST(TIPOSETOR AS STRING) AS TIPOSETOR
    , SAFE_CAST(CIDADE_COD AS STRING) AS CIDADE_COD
    , SAFE_CAST(TIPOACESSO AS STRING) AS TIPOACESSO
    , SAFE_CAST(COMPLEMENTO AS STRING) AS COMPLEMENTO
    , SAFE_CAST(CENTRO_CUSTO AS STRING) AS CENTRO_CUSTO
    , SAFE_CAST(FLEX_CAMPO_14 AS STRING) AS FLEX_CAMPO_14
    , SAFE_CAST(FLEX_CAMPO_15 AS STRING) AS FLEX_CAMPO_15
    , SAFE_CAST(CAST(SUBEMP_CODIGO AS STRING) AS STRING) AS SUBEMP_CODIGO
    , SAFE_CAST(MBAIRRO_CODIGO AS STRING) AS MBAIRRO_CODIGO
    , SAFE_CAST(MBAIRRO_MUNICIPIO_CODIGO AS STRING) AS MBAIRRO_MUNICIPIO_CODIGO

FROM {{ source('brutos_ergon_staging', 'VW_DLK_ERG_HSETOR_')}}