SELECT
    SAFE_CAST(cod_auditoria AS STRING) as id_auditoria,
    SAFE_CAST(ano_base AS INT64) as ano,
    SAFE_CAST(orgao_auditado AS STRING) as orgao,
    SAFE_CAST(cod_meta AS STRING) as codigo_meta,
    SAFE_CAST(orgao_acordo_egpweb AS STRING) as orgao_egpweb,    
    SAFE_CAST(relatorio_da_auditoria_geral_rag AS STRING) as relatorio_auditoria_geral,
    SAFE_CAST(ordem_de_servico AS STRING) as ordem_servico,
    SAFE_CAST(data_do_inicio_da_auditoria AS DATE) as inicio_auditoria,
    SAFE_CAST(data_do_final_da_auditoria AS DATE) as final_auditoria,
    SAFE_CAST(data_do_relatorio AS DATE) as data_relatorio,    
    SAFE_CAST(meta_auditada AS STRING) as descricao_meta,
    SAFE_CAST(resumo_da_auditoria AS STRING) as resumo_auditoria,
    SAFE_CAST(numero_de_testes AS INT64) as quantidade_teste,
    SAFE_CAST(numero_de_fragilidades AS INT64) as fragilidades,
    SAFE_CAST(penalidade AS BOOL) as penalidade,
    SAFE_CAST(penalidade_nota AS FLOAT64) as penalidade_nota,
    SAFE_CAST(penalidade_bonus AS FLOAT64) as penalidade_bonus,
    SAFE_CAST(inicio_do_periodo_apurado AS DATE) as inicio_periodo_apurado,
    SAFE_CAST(final_do_periodo_apurado AS DATE) as final_periodo_apurado,
    SAFE_CAST(numero_de_recomendacoes AS INT64) as recomendacoes
FROM `planejamento_gestao_acordo_resultados_staging.auditoria`