version: 2
models :
  - name: comentario
    description: "**Descrição**: Comentários feitos pelos analistas de gerenciamento
      de projetos e metas sobre as apurações mensais do desempenho dos órgãos para
      se alcançar a meta. Pode haver mais de um comentário sobre uma meta, feitos
      pelo mesmo analista ou por vários.\n**Frequência de atualização**: Mensal\n
      **Cobertura temporal**: Desde 2013 até a data corrente.\n**Órgão gestor dos
      dados**: Secretaria Municipal de Fazenda e Planejamento (SMFP)\n**Publicado
      por**: Bruno Almeida\n**Publicado por (email)**: brunodepauloalmeida@gmail.com\n"
    columns:
      - name: id_camada
        description: Código identificador da meta, do órgão ou da área de resultado
          dependendo do atributo indice_camada.
      - name: indice_camada
        description: Nos diz a quem está associado o comentário. 1 - Uma meta, 2 -
          Todas as metas de um órgão.
      - name: ano
        description: Ano referente à meta comentada.
      - name: mes
        description: Mês referente à meta comentada.
      - name: comentario
        description: Comentário feito pelo analista.
      - name: numero_analista
        description: Código identificador do analista que fez o comentário.
      - name: ordem
        description: Ordem do comentário. Pode haver mais de um comentário para uma
          mesma meta em um mesmo período (ano e mês).
  - name: chance
    description: "**Descrição**: Chance, avaliada pelo analista de gestão de projetos,
      em determinado mês, de atingimento de meta de Acordo de Resultados.\n**Frequência
      de atualização**: Mensal\n**Cobertura temporal**: Desde 2013 até a data corrente.\n
      **Órgão gestor dos dados**: Secretaria Municipal de Fazenda e Planejamento (SMFP)\n
      **Publicado por**: Bruno Almeida\n**Publicado por (email)**: brunodepauloalmeida@gmail.com\n"
    columns:
      - name: id_camada
        description: Código identificador da meta, do órgão ou da área de resultado
          dependendo do atributo indice_camada.
      - name: indice_camada
        description: Nos diz a quem está associada a chance.  1 - Uma meta, 2 - Todas
          as metas de um órgão.
      - name: ano
        description: Ano do indicador para o qual foi avaliada a chance.
      - name: mes
        description: Mês do indicador para o qual foi avaliada a chance.
      - name: cor_chance
        description: "Diz qual a tendência de cumprimento da meta, de acordo com a
          seguinte tradução:\r\nse ch.cor_chance = '1' então 'Indefinida\"', \r\n
          se ch.cor_chance = '2' então 'Não cumprida',\r\nse ch.cor_chance = '3' então
          'Atraso grave',\r\nse ch.cor_chance = '4' então 'Atraso Recuperável',\r\n
          se ch.cor_chance = '5' então 'Andamento Satisfatório',\r\nse ch.cor_chance
          = '6' então 'Cumprida'."
  - name: nota_meta
    description: "**Descrição**: Nota dada pela prefeitura para o que foi alcançado
      por um órgão para determinado identificador de meta. Uma meta pode ter vários
      identificadores, um para cada indicador associado a ela.\n**Frequência de atualização**:
      Mensal\n**Cobertura temporal**: Desde 2022 até a data corrente.\n**Órgão gestor
      dos dados**: Secretaria Municipal de Fazenda e Planejamento (SMFP)\n**Publicado
      por**: Bruno Almeida\n**Publicado por (email)**: brunodepauloalmeida@gmail.com\n"
    columns:
      - name: id_meta
        description: Identificador da meta para a qual a nota foi dada. Existe um
          identificador para cada meta, por órgão e por indicador.
      - name: ano
        description: Ano para o qual a nota foi dada.
      - name: mes
        description: Mês para o qual a nota foi dada.
      - name: valor
        description: Valor da nota.
  - name: indicador
    description: "**Descrição**: Indicadores, apurados mensalmente, que servem para
      medir o quanto foi alcançado das metas dos acordos de resultados.\n**Frequência
      de atualização**: Mensal\n**Cobertura temporal**: Desde 2022 até a data corrente.\n
      **Órgão gestor dos dados**: Secretaria Municipal de Fazenda e Planejamento (SMFP)\n
      **Publicado por**: Bruno Almeida\n**Publicado por (email)**: brunodepauloalmeida@gmail.com\n"
    columns:
      - name: id_meta
        description: Código identificador da meta medida pelo indicador.
      - name: ano
        description: Ano de aferição do indicador.
      - name: mes
        description: Mês de aferição do indicador.
      - name: valor
        description: Valor alcançado pelo indicador no mês. Pode ser um dado número,
          um percentual ou uma sinalização indicando que foi entregue ou não.
  - name: meta
    description: "**Descrição**: Metas, por indicador e por órgão, dos Acordos de
      Resultados. Se uma meta tiver dois indicadores ela aparecerá duas vezes. Uma
      mesma meta que inclua mais de um órgão também aparecerá mais de uma vez.\n**Frequência
      de atualização**: Mensal\n**Cobertura temporal**: Desde 2013 até a data corrente.\n
      **Órgão gestor dos dados**: Secretaria Municipal de Fazenda e Planejamento (SMFP)\n
      **Publicado por**: Bruno Almeida\n**Publicado por (email)**: brunodepauloalmeida@gmail.com\n"
    columns:
      - name: id_meta
        description: Código identificador da meta por indicador e por órgão.
      - name: descricao
        description: Descrição da meta.
      - name: observacao
        description: Observação sobre a meta. Registra detalhes como divergência entre
          os indicadores do PE e AR, metas que são desdobradas por ter mais de 1 indicador,
          detalhes que ajudam na medição do indicador e que estarão no Anexo 2, etc..
      - name: ordem
        description: Ordem da meta no Acordo de Resultados no órgão. Metas Estratégicas
          são as primeiras, depois vêm as Complementares e depois a Meta de Performance
      - name: referencia
        description: Valor usado como referência para comparação com o valor desejado
          para o indicador usado para medir a meta.
      - name: data_referencia
        description: Data que diz respeito ao valor de referência.
      - name: ano
        description: Ano do acordo de resultados relacionado à meta.
      - name: fonte
        description: Órgão interno ou órgão externo que nos dá o valor indicador.
      - name: formula
        description: Fórmula de cálculo do indicador.
      - name: tipo_acompanhamento
        description: Indica se a meta é acumulada ou se é uma média dos valores.
      - name: tipo_gestao
        description: Indica se a meta é estratégica ou complementar.
      - name: id_orgao
        description: Código identificador do órgão associado a meta.
      - name: orgao
        description: Nome do órgão associado a meta.
      - name: sigla_orgao
        description: Sigla do órgão associado a meta.
      - name: unidade_medida
        description: Unidade de medida do indicador.
      - name: numero_meta_mae
        description: Identificador da meta mãe. Meta de ano anterior usada como referência,
          para aproveitamento de informações, para a meta atual.
      - name: area_resultado
        description: Área de resultado do plano estratégico referente a meta.
      - name: tipo
        description: Indica se a meta é estratégica, complementar ou de performance.
          Metas Estratégicas são as mais relevantes e é preciso atingir um número
          mínimo de metas estratégicas para que sejam consideradas as metas complementares
          e a meta performance. Metas complementares são metas de menor peso na nota
          final do órgão e a meta performance registra o desempenho do órgão avaliado
          por diferentes órgãos.
      - name: indicador_recurso
        description: Identifica se o órgão apresentou recurso para a meta. Um órgão
          pode fazer o recurso para retirar a meta do seu acordo de resultado ou ter
          seu resultado aceito.
      - name: indicador_auditoria
        description: Identifica se a meta foi selecionada para auditoria pela CGM.
      - name: janeiro
        description: Desdobramento da meta no mês de janeiro. Objetiva registrar o
          valor planejado, do indicador, no mês para fins de acompanhamento mensal
          da mesma.
      - name: fevereiro
        description: Desdobramento da meta no mês de fevereiro. Objetiva registrar
          o valor planejado, do indicador, no mês para fins de acompanhamento mensal
          da mesma.
      - name: marco
        description: Desdobramento da meta no mês de março. Objetiva registrar o valor
          planejado, do indicador, no mês para fins de acompanhamento mensal da mesma.
      - name: abril
        description: Desdobramento da meta no mês de abril. Objetiva registrar o valor
          planejado, do indicador, no mês para fins de acompanhamento mensal da mesma.
      - name: maio
        description: Desdobramento da meta no mês de maio. Objetiva registrar o valor
          planejado, do indicador, no mês para fins de acompanhamento mensal da mesma.
      - name: junho
        description: Desdobramento da meta no mês de junho. Objetiva registrar o valor
          planejado, do indicador, no mês para fins de acompanhamento mensal da mesma.
      - name: julho
        description: Desdobramento da meta no mês de julho. Objetiva registrar o valor
          planejado, do indicador, no mês para fins de acompanhamento mensal da mesma.
      - name: agosto
        description: Desdobramento da meta no mês de agosto. Objetiva registrar o
          valor planejado, do indicador, no mês para fins de acompanhamento mensal
          da mesma.
      - name: setembro
        description: Desdobramento da meta no mês de setembro. Objetiva registrar
          o valor planejado, do indicador, no mês para fins de acompanhamento mensal
          da mesma.
      - name: outubro
        description: Desdobramento da meta no mês de outubro. Objetiva registrar o
          valor planejado, do indicador, no mês para fins de acompanhamento mensal
          da mesma.
      - name: novembro
        description: Desdobramento da meta no mês de novembro. Objetiva registrar
          o valor planejado, do indicador, no mês para fins de acompanhamento mensal
          da mesma.
      - name: dezembro
        description: Desdobramento da meta no mês de dezembro. Objetiva registrar
          o valor planejado, do indicador, no mês para fins de acompanhamento mensal
          da mesma.
