{{ 
    config( alias='dependente',schema='recursos_humanos_ergon_comlurb') 
}}
SELECT 
    SAFE_CAST(REGEXP_REPLACE(TRIM(num_cert), r'\.0$', '') AS STRING) AS id_certidao_nascimento_casamento,
    SAFE_CAST(TRIM(livro_a_cert) AS STRING) AS numero_livro_nascimento_casamento,
    SAFE_CAST(TRIM(folha_cert) AS STRING) AS numero_folha_nascimento_casamento,
    SAFE_CAST(TRIM(cartorio_cert) AS STRING) AS numero_cartorio_nascimento_casamento,
    SAFE_CAST(TRIM(flex_campo_01) AS STRING) AS estado_civil,
    SAFE_CAST(TRIM(flex_campo_02) AS STRING) AS nome_mae,
    SAFE_CAST(TRIM(uf_cart) AS STRING) AS sigla_uf_cartorio,
    SAFE_CAST(TRIM(municipio_cart) AS STRING) AS municipio_cartorio,
    SAFE_CAST(TRIM(tipodoc_cert) AS STRING) AS tipo_certidao,
    SAFE_CAST(REGEXP_REPLACE(TRIM(numrg), r'\.0$', '') AS STRING) AS id_rg,
    SAFE_CAST(TRIM(tiporg) AS STRING) AS tipo_rg,
    SAFE_CAST(TRIM(orgaorg) AS STRING) AS orgao_rg,
    SAFE_CAST(TRIM(ufrg) AS STRING) AS sigla_uf_rg,
    SAFE_CAST(TRIM(tipodoc_cert_fim) AS STRING) AS tipo_certidao_fim,
    SAFE_CAST(DATE(dt_cert_fim) AS DATE) AS data_certidao_fim,
    SAFE_CAST(TRIM(num_cert_fim) AS STRING) AS numero_certidao_fim,
    SAFE_CAST(TRIM(livro_cert_fim) AS STRING) AS numero_livro_certidao_fim,
    SAFE_CAST(TRIM(folha_cert_fim) AS STRING) AS numero_folha_certidao_fim,
    SAFE_CAST(TRIM(cartorio_cert_fim) AS STRING) AS numero_cartorio_certidao_fim,
    SAFE_CAST(TRIM(uf_cart_fim) AS STRING) AS sigla_uf_cartorio_fim,
    SAFE_CAST(TRIM(municipio_cart_fim) AS STRING) AS municipio_cartorio_certidao_fim,
    SAFE_CAST(DATE(expedrg) AS DATE) AS data_expedicao_rg,
    SAFE_CAST(TRIM(matricula_cert) AS STRING) AS matricula_certidao,
    SAFE_CAST(TRIM(matricula_cert_fim) AS STRING) AS matricula_certidao_fim,
    SAFE_CAST(TRIM(tipodepen) AS STRING) AS tipo_dependente,
    SAFE_CAST(REGEXP_REPLACE(TRIM(id_reg), r'\.0$', '') AS STRING) AS id_dependente,
    SAFE_CAST(REGEXP_REPLACE(TRIM(numfunc), r'\.0$', '') AS STRING) AS id_funcionario,
    SAFE_CAST(REGEXP_REPLACE(TRIM(numero), r'\.0$', '') AS INT64) AS numero_dependente,
    SAFE_CAST(TRIM(nome) AS STRING) AS nome,
    SAFE_CAST(TRIM(sexo) AS STRING) AS sexo,
    SAFE_CAST(DATE(dtnasc) AS DATE) AS data_nascimento,
    SAFE_CAST(TRIM(parentesco) AS STRING) AS parentesco,
    SAFE_CAST(REGEXP_REPLACE(TRIM(cpf), r'\.0$', '') AS STRING) AS id_cpf,
    SAFE_CAST(TRIM(tipologender) AS STRING) AS tipo_logradouro,
    SAFE_CAST(TRIM(nomelogender) AS STRING) AS logradouro,
    SAFE_CAST(REGEXP_REPLACE(TRIM(numender), r'\.0$', '') AS INT64) AS numero_porta,
    SAFE_CAST(TRIM(complender) AS STRING) AS complemento_numero_porta,
    SAFE_CAST(TRIM(bairroender) AS STRING) AS bairro,
    SAFE_CAST(TRIM(cepender) AS STRING) AS cep,
    SAFE_CAST(TRIM(conta) AS STRING) AS conta,
    SAFE_CAST(TRIM(tipopag) AS STRING) AS tipo_pagamento,
    SAFE_CAST(TRIM(cidadeender) AS STRING) AS municipio,
    SAFE_CAST(TRIM(ufender) AS STRING) AS sigla_uf,
    SAFE_CAST(TRIM(telefone) AS STRING) AS telefone,
    SAFE_CAST(TRIM(banco) AS STRING) AS banco,
    SAFE_CAST(TRIM(agencia) AS STRING) AS agencia,
FROM rj-smfp.recursos_humanos_ergon_comlurb_staging.dependente AS t