{{ 
    config( alias='licenca_afastamento',schema='recursos_humanos_ergon_comlurb') 
}}

SELECT 
    SAFE_CAST(REGEXP_REPLACE(TRIM(numfunc), r'\.0$', '') AS STRING) AS id_funcionario,
    SAFE_CAST(REGEXP_REPLACE(TRIM(numvinc), r'\.0$', '') AS STRING) AS id_vinculo,
    SAFE_CAST(REGEXP_REPLACE(TRIM(emp_codigo), r'\.0$', '') AS STRING) AS id_empresa,
    SAFE_CAST(REGEXP_REPLACE(id_reg, r'\.0$', '') AS STRING) AS id_registro,
    SAFE_CAST(DATE(dtini) AS DATE) AS data_inicio,
    SAFE_CAST(DATE(dtfim) AS DATE) AS data_fim,
    SAFE_CAST(TRIM(tipofreq) AS STRING) AS tipo_frequencia,
    SAFE_CAST(REGEXP_REPLACE(TRIM(codfreq), r'\.0$', '') AS STRING) AS id_frequencia,
    SAFE_CAST(TRIM(motivo) AS STRING) AS motivo,
    SAFE_CAST(DATE(dtprevfim) AS DATE) AS data_previsao_fim,
    SAFE_CAST(TRIM(reqlicafast) AS STRING) AS reqlicafast,
    SAFE_CAST(TRIM(resultpront) AS STRING) AS resultpront,
    SAFE_CAST(TRIM(pontlei) AS STRING) AS publicacao_diario_oficial,
    SAFE_CAST(TRIM(pontpubl) AS STRING) AS pontpubl,
    SAFE_CAST(TRIM(pontproc) AS STRING) AS pontproc,
    SAFE_CAST(SAFE.PARSE_DATETIME("%d/%m/%Y %H:%M:%S", TRIM(flex_campo_01)) AS DATETIME) AS flex_campo_01,
    SAFE_CAST(TRIM(flex_campo_02) AS STRING) AS flex_campo_02,
    SAFE_CAST(TRIM(flex_campo_03) AS STRING) AS flex_campo_03,
    SAFE_CAST(TRIM(flex_campo_04) AS STRING) AS flex_campo_04,
    SAFE_CAST(TRIM(flex_campo_05) AS STRING) AS flex_campo_05,
    SAFE_CAST(TRIM(flex_campo_06) AS STRING) AS flex_campo_06,
    SAFE_CAST(TRIM(flex_campo_07) AS STRING) AS flex_campo_07,
    SAFE_CAST(TRIM(flex_campo_08) AS STRING) AS flex_campo_08,
    SAFE_CAST(TRIM(flex_campo_09) AS STRING) AS flex_campo_09,
    SAFE_CAST(TRIM(flex_campo_10) AS STRING) AS flex_campo_10,
    SAFE_CAST(TRIM(flex_campo_11) AS STRING) AS flex_campo_11,
    SAFE_CAST(TRIM(flex_campo_12) AS STRING) AS flex_campo_12,
    SAFE_CAST(TRIM(flex_campo_13) AS STRING) AS flex_campo_13,
    SAFE_CAST(TRIM(flex_campo_14) AS STRING) AS flex_campo_14,
    SAFE_CAST(TRIM(flex_campo_15) AS STRING) AS flex_campo_15,
    SAFE_CAST(TRIM(flex_campo_16) AS STRING) AS flex_campo_16,
    SAFE_CAST(TRIM(flex_campo_17) AS STRING) AS flex_campo_17,
    SAFE_CAST(TRIM(flex_campo_18) AS STRING) AS flex_campo_18,
    SAFE_CAST(TRIM(flex_campo_19) AS STRING) AS flex_campo_19,
    SAFE_CAST(TRIM(flex_campo_20) AS STRING) AS flex_campo_20,
    SAFE_CAST(TRIM(flex_campo_21) AS STRING) AS flex_campo_21,
    SAFE_CAST(TRIM(flex_campo_22) AS STRING) AS flex_campo_22,
    SAFE_CAST(TRIM(flex_campo_23) AS STRING) AS flex_campo_23,
    SAFE_CAST(TRIM(flex_campo_24) AS STRING) AS flex_campo_24,
    SAFE_CAST(TRIM(flex_campo_25) AS STRING) AS flex_campo_25,
    SAFE_CAST(TRIM(flex_campo_26) AS STRING) AS flex_campo_26,
    SAFE_CAST(TRIM(flex_campo_27) AS STRING) AS flex_campo_27,
    SAFE_CAST(TRIM(flex_campo_28) AS STRING) AS flex_campo_28,
    SAFE_CAST(TRIM(flex_campo_29) AS STRING) AS flex_campo_29,
    SAFE_CAST(TRIM(flex_campo_30) AS STRING) AS flex_campo_30,
    SAFE_CAST(TRIM(flex_campo_31) AS STRING) AS flex_campo_31,
    SAFE_CAST(TRIM(flex_campo_32) AS STRING) AS flex_campo_32,
    SAFE_CAST(TRIM(flex_campo_33) AS STRING) AS flex_campo_33,
    SAFE_CAST(TRIM(flex_campo_34) AS STRING) AS flex_campo_34,
    SAFE_CAST(TRIM(flex_campo_35) AS STRING) AS flex_campo_35,
    SAFE_CAST(TRIM(flex_campo_36) AS STRING) AS flex_campo_36,
    SAFE_CAST(TRIM(flex_campo_37) AS STRING) AS flex_campo_37,
    SAFE_CAST(TRIM(flex_campo_38) AS STRING) AS flex_campo_38,
    SAFE_CAST(TRIM(flex_campo_39) AS STRING) AS flex_campo_39,
    SAFE_CAST(TRIM(flex_campo_40) AS STRING) AS flex_campo_40,
    SAFE_CAST(TRIM(flex_campo_41) AS STRING) AS flex_campo_41,
    SAFE_CAST(TRIM(flex_campo_42) AS STRING) AS flex_campo_42,
    SAFE_CAST(TRIM(flex_campo_43) AS STRING) AS flex_campo_43,
    SAFE_CAST(TRIM(flex_campo_44) AS STRING) AS flex_campo_44,
    SAFE_CAST(TRIM(flex_campo_45) AS STRING) AS flex_campo_45,
    SAFE_CAST(TRIM(flex_campo_46) AS STRING) AS flex_campo_46,
    SAFE_CAST(TRIM(flex_campo_47) AS STRING) AS flex_campo_47,
    SAFE_CAST(TRIM(flex_campo_48) AS STRING) AS flex_campo_48,
    SAFE_CAST(TRIM(flex_campo_49) AS STRING) AS flex_campo_49,
    SAFE_CAST(TRIM(flex_campo_50) AS STRING) AS flex_campo_50,
    SAFE_CAST(TRIM(flex_campo_51) AS STRING) AS flex_campo_51,
    SAFE_CAST(TRIM(flex_campo_52) AS STRING) AS flex_campo_52,
    SAFE_CAST(TRIM(flex_campo_53) AS STRING) AS flex_campo_53,
    SAFE_CAST(TRIM(flex_campo_54) AS STRING) AS flex_campo_54,
    SAFE_CAST(TRIM(flex_campo_55) AS STRING) AS flex_campo_55,
    SAFE_CAST(TRIM(flex_campo_56) AS STRING) AS flex_campo_56,
    SAFE_CAST(TRIM(flex_campo_57) AS STRING) AS flex_campo_57,
    SAFE_CAST(TRIM(flex_campo_58) AS STRING) AS flex_campo_58,
    SAFE_CAST(TRIM(flex_campo_59) AS STRING) AS flex_campo_59,
    SAFE_CAST(TRIM(flex_campo_60) AS STRING) AS flex_campo_60,
    SAFE_CAST(TRIM(flex_campo_61) AS STRING) AS flex_campo_61,
    SAFE_CAST(TRIM(flex_campo_62) AS STRING) AS flex_campo_62,
    SAFE_CAST(TRIM(flex_campo_63) AS STRING) AS flex_campo_63,
    SAFE_CAST(TRIM(flex_campo_64) AS STRING) AS flex_campo_64,
    SAFE_CAST(TRIM(flex_campo_65) AS STRING) AS flex_campo_65,
FROM rj-smfp.recursos_humanos_ergon_comlurb_staging.licenca_afastamento AS t





