version: 2
models :
  - name: averbacoes_contagem
    description: "**Descrição**: Nesta tabela são armazenadas informações referentes\
      \ sobre finalidade de contagem e total do tempo de contagem referentes a períodos\
      \ averbados pelos servidores.\n**Frequência de atualização**: Nunca\n**Cobertura\
      \ temporal**: Não informado\n**Órgão gestor dos dados**: Não informado\n**Publicado\
      \ por**: Não informado\n**Publicado por (email)**: naoinformado@naoinformado.com\n"
    columns:
      - name: id_funcionario
        description: Número do funcionário gerado pelo ERGON.
      - name: id_vinculo
        description: Número do vínculo relativo ao pagamento.
      - name: id_averbacao
        description: Chave gerada pelo banco para registro de averbação.
      - name: finalidade
        description: Tipo da finalidade da averbação.
      - name: dias
        description: Total de dias averbados para determinada finalidade.
  - name: averbacoes_contagem
    description: "**Descrição**: Nesta tabela são armazenadas informações referentes\
      \ sobre finalidade de contagem e total do tempo de contagem referentes a períodos\
      \ averbados pelos servidores.\n**Frequência de atualização**: Nunca\n**Cobertura\
      \ temporal**: Não informado\n**Órgão gestor dos dados**: Não informado\n**Publicado\
      \ por**: Não informado\n**Publicado por (email)**: naoinformado@naoinformado.com\n"
    columns:
      - name: id_funcionario
        description: Número do funcionário gerado pelo ERGON.
      - name: id_vinculo
        description: Número do vínculo relativo ao pagamento.
      - name: id_averbacao
        description: Chave gerada pelo banco para registro de averbação.
      - name: finalidade
        description: Tipo da finalidade da averbação.
      - name: dias
        description: Total de dias averbados para determinada finalidade.
  - name: averbacoes_contagem
    description: "**Descrição**: Nesta tabela são armazenadas informações referentes\
      \ sobre finalidade de contagem e total do tempo de contagem referentes a períodos\
      \ averbados pelos servidores.\n**Frequência de atualização**: Nunca\n**Cobertura\
      \ temporal**: Não informado\n**Órgão gestor dos dados**: Não informado\n**Publicado\
      \ por**: Não informado\n**Publicado por (email)**: naoinformado@naoinformado.com\n"
    columns:
      - name: id_funcionario
        description: Número do funcionário gerado pelo ERGON.
      - name: id_vinculo
        description: Número do vínculo relativo ao pagamento.
      - name: id_averbacao
        description: Chave gerada pelo banco para registro de averbação.
      - name: finalidade
        description: Tipo da finalidade da averbação.
      - name: dias
        description: Total de dias averbados para determinada finalidade.
  - name: averbacoes_contagem
    description: "**Descrição**: Nesta tabela são armazenadas informações referentes\
      \ sobre finalidade de contagem e total do tempo de contagem referentes a períodos\
      \ averbados pelos servidores.\n**Frequência de atualização**: Nunca\n**Cobertura\
      \ temporal**: Não informado\n**Órgão gestor dos dados**: Não informado\n**Publicado\
      \ por**: Não informado\n**Publicado por (email)**: naoinformado@naoinformado.com\n"
    columns:
      - name: id_funcionario
        description: Número do funcionário gerado pelo ERGON.
      - name: id_vinculo
        description: Número do vínculo relativo ao pagamento.
      - name: id_averbacao
        description: Chave gerada pelo banco para registro de averbação.
      - name: finalidade
        description: Tipo da finalidade da averbação.
      - name: dias
        description: Total de dias averbados para determinada finalidade.
  - name: averbacoes_contagem
    description: "**Descrição**: Nesta tabela são armazenadas informações referentes\
      \ sobre finalidade de contagem e total do tempo de contagem referentes a períodos\
      \ averbados pelos servidores.\n**Frequência de atualização**: Nunca\n**Cobertura\
      \ temporal**: Não informado\n**Órgão gestor dos dados**: Não informado\n**Publicado\
      \ por**: Não informado\n**Publicado por (email)**: naoinformado@naoinformado.com\n"
    columns:
      - name: id_funcionario
        description: Número do funcionário gerado pelo ERGON.
      - name: id_vinculo
        description: Número do vínculo relativo ao pagamento.
      - name: id_averbacao
        description: Chave gerada pelo banco para registro de averbação.
      - name: finalidade
        description: Tipo da finalidade da averbação.
      - name: dias
        description: Total de dias averbados para determinada finalidade.
  - name: averbacoes_contagem
    description: "**Descrição**: Nesta tabela são armazenadas informações referentes\
      \ sobre finalidade de contagem e total do tempo de contagem referentes a períodos\
      \ averbados pelos servidores.\n**Frequência de atualização**: Nunca\n**Cobertura\
      \ temporal**: Não informado\n**Órgão gestor dos dados**: Não informado\n**Publicado\
      \ por**: Não informado\n**Publicado por (email)**: naoinformado@naoinformado.com\n"
    columns:
      - name: id_funcionario
        description: Número do funcionário gerado pelo ERGON.
      - name: id_vinculo
        description: Número do vínculo relativo ao pagamento.
      - name: id_averbacao
        description: Chave gerada pelo banco para registro de averbação.
      - name: finalidade
        description: Tipo da finalidade da averbação.
      - name: dias
        description: Total de dias averbados para determinada finalidade.
  - name: averbacoes_contagem
    description: "**Descrição**: Nesta tabela são armazenadas informações referentes\
      \ sobre finalidade de contagem e total do tempo de contagem referentes a períodos\
      \ averbados pelos servidores.\n**Frequência de atualização**: Nunca\n**Cobertura\
      \ temporal**: Não informado\n**Órgão gestor dos dados**: Não informado\n**Publicado\
      \ por**: Não informado\n**Publicado por (email)**: naoinformado@naoinformado.com\n"
    columns:
      - name: id_funcionario
        description: Número do funcionário gerado pelo ERGON.
      - name: id_vinculo
        description: Número do vínculo relativo ao pagamento.
      - name: id_averbacao
        description: Chave gerada pelo banco para registro de averbação.
      - name: finalidade
        description: Tipo da finalidade da averbação.
      - name: dias
        description: Total de dias averbados para determinada finalidade.
  - name: averbacoes_contagem
    description: "**Descrição**: Nesta tabela são armazenadas informações referentes\
      \ sobre finalidade de contagem e total do tempo de contagem referentes a períodos\
      \ averbados pelos servidores.\n**Frequência de atualização**: Nunca\n**Cobertura\
      \ temporal**: Não informado\n**Órgão gestor dos dados**: Não informado\n**Publicado\
      \ por**: Não informado\n**Publicado por (email)**: naoinformado@naoinformado.com\n"
    columns:
      - name: id_funcionario
        description: Número do funcionário gerado pelo ERGON.
      - name: id_vinculo
        description: Número do vínculo relativo ao pagamento.
      - name: id_averbacao
        description: Chave gerada pelo banco para registro de averbação.
      - name: finalidade
        description: Tipo da finalidade da averbação.
      - name: dias
        description: Total de dias averbados para determinada finalidade.
  - name: averbacoes_contagem
    description: "**Descrição**: Nesta tabela são armazenadas informações referentes\
      \ sobre finalidade de contagem e total do tempo de contagem referentes a períodos\
      \ averbados pelos servidores.\n**Frequência de atualização**: Nunca\n**Cobertura\
      \ temporal**: Não informado\n**Órgão gestor dos dados**: Não informado\n**Publicado\
      \ por**: Não informado\n**Publicado por (email)**: naoinformado@naoinformado.com\n"
    columns:
      - name: id_funcionario
        description: Número do funcionário gerado pelo ERGON.
      - name: id_vinculo
        description: Número do vínculo relativo ao pagamento.
      - name: id_averbacao
        description: Chave gerada pelo banco para registro de averbação.
      - name: finalidade
        description: Tipo da finalidade da averbação.
      - name: dias
        description: Total de dias averbados para determinada finalidade.
