SELECT 
    SAFE_CAST(DATE(dtini_cessao) AS DATE) AS data_inicio_cessao,
    SAFE_CAST(DATE(dtfim_cessao) AS DATE) AS data_fim_cessao,
    SAFE_CAST(REGEXP_REPLACE(TRIM(numfunc), r'\.0$', '') AS STRING) AS id_funcionario,
    SAFE_CAST(REGEXP_REPLACE(TRIM(numero), r'\.0$', '') AS INT64) AS numero_vinculo,
    SAFE_CAST(DATE(dtnom) AS DATE) AS data_nomeacao,
    SAFE_CAST(TRIM(tipovinc) AS STRING) AS tipo_regime_juridico,
    SAFE_CAST(TRIM(categoria) AS STRING) AS categoria,
    SAFE_CAST(TRIM(desconta_ir) AS STRING) AS desconta_ir,
    SAFE_CAST(TRIM(motivo) AS STRING) AS descricao_provimento,
    SAFE_CAST(TRIM(classifconc) AS STRING) AS classificacao_concurso,
    SAFE_CAST(DATE(dtconc) AS DATE) AS data_concurso,
    SAFE_CAST(DATE(dtopfgts) AS DATE) AS data_opcao_fgts,
    SAFE_CAST(DATE(dtinicontr) AS DATE) AS data_inicio_contrato,
    SAFE_CAST(DATE(dtfimcontr) AS DATE) AS data_fim_contrato,
    SAFE_CAST(DATE(dtprorrogcontr) AS DATE) AS data_prorrogacao_contrato,
    SAFE_CAST(DATE(dtaposent) AS DATE) AS data_aposentadoria,
    SAFE_CAST(TRIM(tipoapos) AS STRING) AS tipo_aposentadoria,
    SAFE_CAST(DATE(dtvac) AS DATE) AS data_vacancia,
    SAFE_CAST(REGEXP_REPLACE(TRIM(formavac), r'\.0$', '') AS STRING) AS id_vacancia,
    SAFE_CAST(TRIM(numvincant) AS STRING) AS numero_vinculo_anterior,
    SAFE_CAST(TRIM(numvincpos) AS STRING) AS numero_vinculo_posterior,
    SAFE_CAST(TRIM(tipoorg_req) AS STRING) AS tipo_orgao_origem,
    SAFE_CAST(TRIM(funcao_req) AS STRING) AS funcao_orgao_origem,
    SAFE_CAST(TRIM(fone_req) AS STRING) AS telefone_orgao_destino,
    SAFE_CAST(TRIM(motivovac) AS STRING) AS motivo_vacancia,
    SAFE_CAST(TRIM(orgao_ext_req) AS STRING) AS orgao_origem,
    SAFE_CAST(TRIM(tipo_onus_req) AS STRING) AS tipo_onus_requisicao,
    SAFE_CAST(TRIM(tipo_ressarc_req) AS STRING) AS tipo_ressarcimento_requisicao,
    SAFE_CAST(TRIM(tipo_req) AS STRING) AS tipo_requisicao,
    SAFE_CAST(TRIM(flex_campo_01) AS STRING) AS tipo_origem,
    SAFE_CAST(REGEXP_REPLACE(TRIM(flex_campo_05), r'\.0$', '') AS STRING) AS id_processo,
    SAFE_CAST(TRIM(flex_campo_09) AS STRING) AS contrato_empregado_cedido_suspenso,
    SAFE_CAST(TRIM(flex_campo_18) AS STRING) AS preenchido_cota,
    SAFE_CAST(REGEXP_REPLACE(TRIM(emp_codigo), r'\.0$', '') AS STRING) AS id_empresa,
    SAFE_CAST(DATE(dtposse) AS DATE) AS data_posse,
    SAFE_CAST(DATE(dtexerc) AS DATE) AS data_inicio_exercicio,
    SAFE_CAST(TRIM(regimejur) AS STRING) AS regime_juridico,
    SAFE_CAST(DATE(dt_pgto_ate) AS DATE) AS data_pagamento_recisao,
FROM rj-smfp.recursos_humanos_ergon_comlurb_staging.vinculo AS t