name: Query Automation

on:
  pull_request_target:
    types:
      - labeled
env:
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}

jobs:
  create-queries:
    name: Create a basic treated query from Google Sheets
    runs-on: ubuntu-latest
    if: github.event.label.name == 'create-basic-query'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python version
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Python dependencies for actions
        run: |-
          pip install -r requirements-actions.txt

      - name: Checkout to the head ref
        run: |-
          git fetch --depth=1
          git checkout ${{ github.head_ref }}

      - name: Update query
        run: |-
          python3 .github/workflows/scripts/query-automation.py

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update query'
